# Generated by Django 5.1.4 on 2024-12-11 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('takimlar', '0001_initial'),
        ('ucaklar', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Montaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(auto_now_add=True)),
                ('takim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takimlar.takim')),
                ('ucak', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='montaj', to='ucaklar.ucak')),
            ],
        ),
    ]
