# Generated by Django 5.1.4 on 2024-12-11 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('takimlar', '0001_initial'),
        ('ucaklar', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(blank=True, max_length=150)),
                ('kategori', models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('AKINCI', 'AKINCI'), ('KIZILELMA', 'KIZILELMA')], max_length=50)),
                ('tur', models.CharField(choices=[('KANAT', 'Kanat'), ('GOVDE', 'Gövde'), ('KUYRUK', 'Kuyruk'), ('AVIYONIK', 'Aviyonik')], max_length=50)),
                ('stok', models.PositiveIntegerField(default=0)),
                ('kullanildi', models.BooleanField(default=False)),
                ('takim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takimlar.takim')),
                ('ucak', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ucaklar.ucak')),
            ],
        ),
    ]
