# Generated by Django 5.1.4 on 2024-12-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Takim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=150, unique=True)),
                ('takim_tipi', models.CharField(choices=[('URETIM', 'Üretim Takımı'), ('MONTAJ', 'Montaj Takımı')], max_length=50)),
                ('tur', models.CharField(blank=True, choices=[('KANAT', 'Kanat'), ('GOVDE', 'Gövde'), ('AVIYONIK', 'Aviyonik'), ('KUYRUK', 'Kuyruk')], max_length=50, null=True)),
            ],
        ),
    ]
