# Generated by Django 5.1.4 on 2024-12-11 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('takimlar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('takim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uyeler', to='takimlar.takim')),
            ],
        ),
    ]
